import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'app_name': 'Ayuuto Savings App',
          'groups': 'Groups',
          'all_users': 'All Users',
          'home': 'Home',
          'profile': 'Profile',
          'payments': 'Payments',
          'my_groups': 'My Groups',
          'available_groups': 'Available Groups',
          'settings': 'Settings',
          'total_groups': 'Total Groups',
          'total_members': 'Total Members',
          'upcoming_payments': 'Upcoming \nPayments',
          'completed_payments': 'Completed \nPayments',
          'quick_actions': 'Quick Actions',
          'create_group': 'Create Group',
          'view_groups': 'View Groups',
          'manage_payments': 'Manage Payments',
          'recent_activity': 'Recent Activity',
          'manage_group': 'Manage Group',
          'active_groups': 'Active Groups',
          'complete': 'Complete',
          'no_groups_found': 'No groups found',
          'members': 'Members',
          'monthly': 'Monthly',
          'invite': 'Invite',
          'active': 'Active',
          'round': 'Round',
          'next_payment': 'Next Payment',
          'current_receiver': 'Current Receiver',
          'group_status_pending': 'Group Status Pending',
          'total_amount': 'Total Amount',
          // Add more translations here
        },
        'so_SO': {
          'app_name': 'Ayuuto Savings App',
          'groups': 'Kooxaha',
          'all_users': 'Dhammaan Isticmaaleyaasha',
          'home': 'Guriga',
          'profile': 'Nafaqada',
          'payments': 'Lacag bixinta',
          'my_groups': 'Kooxdayda',
          'available_groups': 'Kooxaha La Heli Karo',
          'total_groups': 'Kooxaha Guud',
          'total_members': 'Xubnaha Guud',
          'upcoming_payments': 'Lacag bixinta \nSoo Socota',
          'completed_payments': 'Lacag bixinta \nLa Dhameeyay',
          'quick_actions': 'Ficilada Degdega ah',
          'create_group': 'Abuur Koox',
          'view_groups': 'Daawo Kooxaha',
          'manage_payments': 'Maaree Lacag bixinta',
          'recent_activity': 'Hawsha Ugu Dambeys',
          'manage_group': 'Maaree Koox',
          'active_groups': 'Kooxaha Firfircoon',
          'complete': 'Dhameystiran',
          'no_groups_found': 'Kooxo lama helin',
          'members': 'Xubnaha',
          'monthly': 'Bil kasta',
          'invite': 'Martiqaad',
          'active': 'Firfircoon',
          'round': 'Wareeg',
          'next_payment': 'Lacag bixinta Xigta',
          'current_receiver': 'Qaataha Hada',
          'group_status_pending': 'Xaaladda Kooxda \nWaqtiga La Sugayo',
          'total_amount': 'Wadarta Lacagta',
          // Add more translations here
        },
      };
}
