import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'app_name': 'Ayuuto Savings App',
          'sign_in': 'Sign In',
          'sign_up': 'Sign Up',
          'email': 'Email',
          'password': 'Password',
          'dont_have_account': 'Don\'t have an account?',
          'forgot_password': 'Forgot Password?',
          'name': 'Name',
          'date_of_birth': 'Date of Birth',
          'already_have_account': 'Already have an account?',
          'forget_password': 'Forget Password',
          'confirm_password': 'Confirm Password',
          'reset_password': 'Reset Password',
          'reset_your_password': 'Reset Your Password',
          'new_password': 'New Password',
          'groups': 'Groups',
          'all_users': 'All Users',
          'home': 'Home',
          'profile': 'Profile',
          'payments': 'Payments',
          'my_groups': 'My Groups',
          'available_groups': 'Available Groups',
          'settings': 'Settings',
          'total_groups': 'Total Groups',
          'total_members': 'Total Members',
          'upcoming_payments': 'Upcoming \nPayments',
          'completed_payments': 'Completed \nPayments',
          'quick_actions': 'Quick Actions',
          'create_group': 'Create Group',
          'view_groups': 'View Groups',
          'manage_payments': 'Manage Payments',
          'recent_activity': 'Recent Activity',
          'manage_group': 'Manage Group',
          'active_groups': 'Active Groups',
          'complete': 'Complete',
          'no_groups_found': 'No groups found',
          'members': 'Members',
          'monthly': 'Monthly',
          'invite': 'Invite',
          'active': 'Active',
          'round': 'Round',
          'next_payment': 'Next Payment',
          'current_receiver': 'Current Receiver',
          'group_status_pending': 'Group Status Pending',
          'total_amount': 'Total Amount',
          'payment_management': 'Payment Management',
          'upcomming': 'Upcoming',
          'completed': 'Completed',
          'full_name': 'Full Name',
          'phone_number': 'Phone Number',
          'group_joined': 'Group Joined',
          'total_pay': 'Total Pay',
          'payment_method': 'Payment Method',
          'add_new': 'Add New',
          'logout': 'Logout',
          'acount_information': 'Account Information',
          'add_new_card': 'Add New Card',
          'enter_card_number': 'Enter Card Number',
          'cancel': 'Cancel',
          'add': 'Add',
          'group_name': 'Group Name',
          'enter_group_name': 'Enter group name',
          'contrubution_amount': 'Contribution Amount',
          'frequency': 'Frequency',
          'amount': 'Amount',
          'select_frequency': 'Select Frequency',
          'maximum_members': 'Maximum Members',
          'enter_maximum_members': 'Enter maximum members',
          'description': 'Description',
          'group_description (optional)': 'Group description (Optional)',
          'your_turn': 'Your Turn',
          'pay_now': 'Pay Now',
          'view_all': 'View All',
          'details': 'Details',
          'payment': 'Payment',
          'upcoming_payment': 'Upcoming Payment',
          'total_contributed': 'Total Contributed',
          'quick_pay': 'Quick Pay',
          'payment_history': 'Payment History',

          // Add more translations here
        },
        'so_SO': {
          'app_name': 'Ayuuto Savings App',
          'sign_in': 'Gali',
          'sign_up': 'Isku Diiwaangeli',
          'email': 'Email',
          'password': 'Furaha',
          'dont_have_account': 'Ma haysatid akoon?',
          'forgot_password': 'Furaha Ma Hilowday?',
          'confirm_password': 'Xaqiji Furaha',
          'name': 'Magaca',
          'date_of_birth': 'Taariikhda Dhalashada',
          'already_have_account': 'Horey u haysatay akoon?',
          'forget_password': 'Hilowday Furaha',
          'reset_password': 'Dib u dejinta Furaha',
          'reset_your_password': 'Dib u dejinta Furahaaga',
          'new_password': 'Furaha Cusub',
          'groups': 'Kooxaha',
          'all_users': 'Dhammaan Isticmaaleyaasha',
          'home': 'Guriga',
          'profile': 'Nafaqada',
          'payments': 'Lacag bixinta',
          'my_groups': 'Kooxdayda',
          'available_groups': 'Kooxaha La Heli Karo',
          'total_groups': 'Kooxaha Guud',
          'total_members': 'Xubnaha Guud',
          'upcoming_payments': 'Lacag bixinta \nSoo Socota',
          'completed_payments': 'Lacag bixinta \nLa Dhameeyay',
          'quick_actions': 'Ficilada Degdega ah',
          'create_group': 'Abuur Koox',
          'view_groups': 'Daawo Kooxaha',
          'manage_payments': 'Maaree Lacag bixinta',
          'recent_activity': 'Hawsha Ugu Dambeys',
          'manage_group': 'Maaree Koox',
          'active_groups': 'Kooxaha Firfircoon',
          'complete': 'Dhameystiran',
          'no_groups_found': 'Kooxo lama helin',
          'members': 'Xubnaha',
          'monthly': 'Bil kasta',
          'invite': 'Martiqaad',
          'active': 'Firfircoon',
          'round': 'Wareeg',
          'next_payment': 'Lacag bixinta Xigta',
          'current_receiver': 'Qaataha Hada',
          'group_status_pending': 'Xaaladda Kooxda \nWaqtiga La Sugayo',
          'total_amount': 'Wadarta Lacagta',
          'payment_management': 'Maareynta Lacag bixinta',
          'upcomming': 'Soo Socota',
          'completed': 'La Dhameeyay',
          'full_name': 'Magaca oo dhan',
          'phone_number': 'Lambarka Taleefanka',
          'group_joined': 'Kooxda La Galay',
          'total_pay': 'Lacagta Guud',
          'payment_method': 'Habka Lacag bixinta',
          'add_new': 'Kudar Cusub',
          'logout': 'Ka bax',
          'acount_information': 'Xogta Akoonka',
          'add_new_card': 'Kudar Kaarka Cusub',
          'enter_card_number': 'Gali Lambarka Kaarka',
          'cancel': 'Jooji',
          'add': 'Kudar',
          'group_name': 'Gali magaca kooxda',
          'enter_group_name': 'Gali magaca kooxda',
          'contrubution_amount': 'Lacagta Kaalmada',
          'frequency': 'Fasax',
          'amount': 'Lacag',
          'select_frequency': 'Dooro Fasaxa',
          'maximum_members': 'Xubnaha ugu badan',
          'enter_maximum_members': 'Gali xubnaha ugu badan',
          'description': 'Sharaxaad',
          'group_description (optional)': 'Sharaxaada Kooxda (Ikhtiyaari)',
          'your_turn': 'Waqtigaaga',
          'pay_now': 'Bixi Hadda',
          'view_all': 'Daawo Dhammaan',
          'details': 'Faahfaahinta',
          'payment': 'Lacag bixinta',
          'upcoming_payment': 'Lacag bixinta \nSoo Socota',
          'total_contributed': 'Lacagta Guud \nee La Bixiyay',
          'quick_pay': 'Lacag Bixinta Degdega ah',
          'payment_history': 'Taariikhda Lacag bixinta',

          // Add more translations here
        },
      };
}
