// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDfUZu99taO9eQx-m7H5t3LgmUcNNcrU',
    appId: '1:863070520778:web:59c36189041c447753bb33',
    messagingSenderId: '863070520778',
    projectId: 'ayuutosavingsapp',
    authDomain: 'ayuutosavingsapp.firebaseapp.com',
    storageBucket: 'ayuutosavingsapp.firebasestorage.app',
    measurementId: 'G-LM4R5EZ0XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWiDa6bX_DmDY0jOXZIELxuVNdL4BVeA',
    appId: '1:863070520778:android:8823f4e96216e44053bb33',
    messagingSenderId: '863070520778',
    projectId: 'ayuutosavingsapp',
    storageBucket: 'ayuutosavingsapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdA1R8EUeU1MkSoDhnQ2AhsPXzVtzOlsg',
    appId: '1:863070520778:ios:62dca24fd46b0d2253bb33',
    messagingSenderId: '863070520778',
    projectId: 'ayuutosavingsapp',
    storageBucket: 'ayuutosavingsapp.firebasestorage.app',
    iosBundleId: 'com.example.ayuutoSavingsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdA1R8EUeU1MkSoDhnQ2AhsPXzVtzOlsg',
    appId: '1:863070520778:ios:62dca24fd46b0d2253bb33',
    messagingSenderId: '863070520778',
    projectId: 'ayuutosavingsapp',
    storageBucket: 'ayuutosavingsapp.firebasestorage.app',
    iosBundleId: 'com.example.ayuutoSavingsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRDfUZu99taO9eQx-m7H5t3LgmUcNNcrU',
    appId: '1:863070520778:web:b14bef00f63f95a053bb33',
    messagingSenderId: '863070520778',
    projectId: 'ayuutosavingsapp',
    authDomain: 'ayuutosavingsapp.firebaseapp.com',
    storageBucket: 'ayuutosavingsapp.firebasestorage.app',
    measurementId: 'G-LKSJGTFV37',
  );
}
