// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs8G7fNbN3YlX__zsh9gOG7rVX2yCgl34',
    appId: '1:818031553895:web:eb1578bcbe71a0a27c93c2',
    messagingSenderId: '818031553895',
    projectId: 'ayuuto-savings-app',
    authDomain: 'ayuuto-savings-app.firebaseapp.com',
    storageBucket: 'ayuuto-savings-app.firebasestorage.app',
    measurementId: 'G-L5R19CEC86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDf6O_hj6S25b6vuQWLXbgJDrbgQCYQ_8',
    appId: '1:818031553895:android:589a6498aa7df84a7c93c2',
    messagingSenderId: '818031553895',
    projectId: 'ayuuto-savings-app',
    storageBucket: 'ayuuto-savings-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCowEhe5DNqW_Ea2gCMagQv_t972mqXXZc',
    appId: '1:818031553895:ios:81f78ab665be1f177c93c2',
    messagingSenderId: '818031553895',
    projectId: 'ayuuto-savings-app',
    storageBucket: 'ayuuto-savings-app.firebasestorage.app',
    iosBundleId: 'com.example.ayuutoSavingsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCowEhe5DNqW_Ea2gCMagQv_t972mqXXZc',
    appId: '1:818031553895:ios:81f78ab665be1f177c93c2',
    messagingSenderId: '818031553895',
    projectId: 'ayuuto-savings-app',
    storageBucket: 'ayuuto-savings-app.firebasestorage.app',
    iosBundleId: 'com.example.ayuutoSavingsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs8G7fNbN3YlX__zsh9gOG7rVX2yCgl34',
    appId: '1:818031553895:web:3878fa3b7d2b09bc7c93c2',
    messagingSenderId: '818031553895',
    projectId: 'ayuuto-savings-app',
    authDomain: 'ayuuto-savings-app.firebaseapp.com',
    storageBucket: 'ayuuto-savings-app.firebasestorage.app',
    measurementId: 'G-4KTBVGB1HQ',
  );

}